// Cinema — a STANDALONE proof-of-feel for the cinematic pixel descent. Reach it at <url>/#cinema.
// Not wired into the game. Demonstrates: a fully-pixel world that SCROLLS in parallax layers while a
// squad of pixel creatures bobs/hops in place (the "world moves with the characters" side-scroller
// trick), on a timed travel → arrive → strike beat. Everything renders pixel-crisp.
//
// Assets are generated by PixelLab (see scripts/pixellab + /tmp/cinema-assets.mjs):
//   /art/env/outer-ring/bg.png   — wide pixel backdrop (sky + cracked-earth ring), scrolls slow
//   /art/env/outer-ring/fg.png   — foreground rocks/embers strip (transparent), scrolls fast
//   /art/creatures/cinderpaw/bob_charv3/frame_0N.png — the hop cycle
// Each falls back gracefully (a tint, or a static rotation) until its art lands.
import { useState, useEffect, useRef } from 'react';

const ENV = '/art/env/outer-ring';
const BOB = '/art/creatures/cinderpaw/bob_charv3';
const ROT = '/art/creatures/cinderpaw/character_v3'; // fallback: rot_00 south, rot_02 east
const BOB_FRAMES = [0, 1, 2, 3].map((i) => `${BOB}/frame_0${i}.png`);

// One creature: cycles its hop frames (falls back to a static rotation + CSS bob if frames 404).
function Mon({ frames, fallback, size, delay = 0, striking = false }) {
  const [i, setI] = useState(0);
  const [broken, setBroken] = useState(false);
  useEffect(() => {
    if (broken) return undefined;
    const t = setInterval(() => setI((n) => (n + 1) % frames.length), 140);
    return () => clearInterval(t);
  }, [broken, frames.length]);
  const src = broken ? fallback : frames[i];
  return (
    <div style={{ width: size, height: size, position: 'relative',
      animation: `cin-bob 0.62s ease-in-out ${delay}s infinite${striking ? ', cin-lunge 1.4s ease-out' : ''}` }}>
      {/* floor shadow */}
      <div style={{ position: 'absolute', bottom: 1, left: '18%', width: '64%', height: size * 0.1,
        borderRadius: '50%', background: 'radial-gradient(ellipse, rgba(0,0,0,0.45), transparent 70%)' }} />
      <img src={src} alt="" onError={() => setBroken(true)}
        style={{ width: '100%', height: '100%', objectFit: 'contain', imageRendering: 'pixelated',
          filter: 'drop-shadow(0 2px 2px rgba(0,0,0,0.4))' }} />
    </div>
  );
}

const PHASES = [
  { id: 'travel', ms: 4200 },
  { id: 'arrive', ms: 1100 },
  { id: 'strike', ms: 1500 },
];

export default function Cinema() {
  const [phase, setPhase] = useState('travel');
  const idx = useRef(0);
  useEffect(() => {
    let alive = true;
    const tick = () => {
      if (!alive) return;
      const p = PHASES[idx.current % PHASES.length];
      setPhase(p.id);
      setTimeout(() => { idx.current += 1; tick(); }, p.ms);
    };
    tick();
    return () => { alive = false; };
  }, []);
  const moving = phase === 'travel';

  // parallax layer: a repeating pixel strip that scrolls left while "moving"
  const layer = (img, dur, h, bottom) => ({
    position: 'absolute', left: 0, right: 0, bottom, height: h,
    backgroundImage: `url(${img})`, backgroundRepeat: 'repeat-x', backgroundSize: 'auto 100%',
    imageRendering: 'pixelated',
    animation: `cin-scroll ${dur}s linear infinite`,
    animationPlayState: moving ? 'running' : 'paused',
  });

  return (
    <div style={{ minHeight: '100vh', background: '#06060c', color: '#e8e8f0', fontFamily: 'system-ui, sans-serif', padding: '18px 16px 50px' }}>
      <style>{`
        @keyframes cin-scroll { from { background-position-x: 0 } to { background-position-x: -768px } }
        @keyframes cin-bob { 0%,100% { transform: translateY(0) } 50% { transform: translateY(-8px) } }
        @keyframes cin-lunge { 0%,100% { transform: translateX(0) } 45% { transform: translateX(16px) scale(1.06) } }
      `}</style>
      <div style={{ maxWidth: 760, margin: '0 auto' }}>
        <div style={{ fontSize: 22, fontWeight: 900, letterSpacing: 1, color: '#ff8a4a' }}>THE DESCENT · Outer Ring</div>
        <div style={{ fontSize: 13, color: '#9aa0b0', marginTop: 4 }}>
          Proof-of-feel: a fully-pixel world scrolls in layers while the squad hops in place. Beat:&nbsp;
          <b style={{ color: phase === 'travel' ? '#ffd0a8' : '#5a5f6e' }}>travel</b> ·&nbsp;
          <b style={{ color: phase === 'arrive' ? '#9be7ff' : '#5a5f6e' }}>arrive</b> ·&nbsp;
          <b style={{ color: phase === 'strike' ? '#ff7a9c' : '#5a5f6e' }}>strike</b>
        </div>

        {/* the stage */}
        <div style={{ position: 'relative', width: '100%', aspectRatio: '16 / 9', marginTop: 14, borderRadius: 12,
          overflow: 'hidden', border: '1px solid #2a2a3a',
          // dusk fallback gradient (shows through until bg.png lands)
          background: 'linear-gradient(180deg, #2a1a2e 0%, #4a2a1e 55%, #1a1208 100%)' }}>

          {/* far backdrop — slow scroll */}
          <div style={{ ...layer(`${ENV}/bg.png`, 26, '100%', 0) }} />

          {/* the ground line the squad stands on */}
          <div style={{ position: 'absolute', left: 0, right: 0, bottom: '20%', height: 2, background: 'rgba(0,0,0,0.25)' }} />

          {/* squad — east-facing travel, bobbing; lead strikes on the strike beat */}
          <div style={{ position: 'absolute', bottom: '20%', left: '50%', transform: 'translateX(-50%)',
            display: 'flex', alignItems: 'flex-end', gap: 6 }}>
            <Mon frames={BOB_FRAMES} fallback={`${ROT}/rot_02.png`} size={66} delay={0.18} />
            <Mon frames={BOB_FRAMES} fallback={`${ROT}/rot_02.png`} size={58} delay={0.34} />
            <Mon frames={BOB_FRAMES} fallback={`${ROT}/rot_00.png`} size={84} delay={0} striking={phase === 'strike'} />
          </div>

          {/* foreground rocks/embers — fast scroll (transparent strip) */}
          <div style={{ ...layer(`${ENV}/fg.png`, 11, '34%', 0), pointerEvents: 'none' }} />
        </div>

        <div style={{ marginTop: 12, fontSize: 12.5, lineHeight: 1.6, color: '#9aa0b0' }}>
          The far ring drifts slow, the foreground rocks rush past — that speed gap is what sells depth and
          motion. The creatures never "walk"; they hop in place while the world slides under them. As we go
          deeper, more layers move (sparks, spores) — until the Drop, where everything goes still.
        </div>
      </div>
    </div>
  );
}
